spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url:  jdbc:mysql://localhost:3306/db_api_security?useSSL=true
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
  thymeleaf:
     prefix: classpath:/templates/
     suffix: .html
     mode: LEGACYHTML5
     encoding: UTF-8
     content-type: text/html
     cache: false
server:
  port: 9999
mybatis:
  mapperLocations: classpath:com/yuchu/springbootsecurityapitest/mapper/*.xml #配置mybatis配置文件路径
  typeAliasesPackage: com.yuchu.springbootsecurityapitest.pojo
logging:
  level:
    org.springframework.security: INFO
    com.yuchu.springbootsecurityapitest.dao: DEBUG
