package com.yuchu.springbootsecurityapitest.dao;

import com.yuchu.springbootsecurityapitest.pojo.Permission;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated
     */

    List<Permission> selectAll();

    List<Permission> selectByAdminUserId(int userId);

}